### ISSUE TITLE
Add import of entire directory to vol180 utility

### ISSUE THREAD

**Issue by vandys** [hperaza/RSX280#1]
I want to start exploring self hosted system builds, so it would be convenient to bulk import an entire source dir.  I've added this to vol180 (when you just do "import <dir>", it pulls all files into your current dir).

I'll submit a PR, but... do you want to continue working on this here?  Otherwise I can fork.

Thanks for an _awesome_ bit of work!

**Comment by hperaza** [comment]
Hello Andy,

Please send me your changes, and I'll upload them to the repository. You can fork the repository as well if you wish.

I used to build the early versions of the system directly on my P112 Z180 machine, but as the system grew larger and I started running out of floppy disk (and later also hard disk) space I switched to cross-development on a Linux machine. When I got the Z280RC board I toyed again with the idea of making some sort of RSX11-like "sysgen" procedure to build the system directly on the Z280 system; I'm attaching here the preliminary command file intended to build the kernel part, but note that it may contain errors since I haven't tested it yet. The command file expects the following directories (or accounts) to exist:

[drvsrc] containing the device driver sources
[syssrc] containing the kernel, startup and initialization task sources
[build] to place the generated output files
Also, the [system] directory is expected to contain the system include files.

Similar command files could be written to build the utilities, the libraries, and to configure the final kernel image.

_Edit: updated the command file, which contained a few errors, added the missing sym2inc program and the bash script I used to import the source files into the CF. Make sure to use LBR and TKB from the latest distribution, which fixes a couple of obscure bugs._

[sysgen.zip](https://github.com/hperaza/RSX280/files/7534481/sysgen.zip)

**Comment by hperaza** [comment]
The above command file successfully compiles the kernel on the Z280RC:

```
Z280RC 2048K RSX280 V6.26

>RED DU4:=LB:
>RED DU4:=SY:
>MOU DU4:
>@SY0:[SYSTEM]STARTUP.CMD
>* Please enter Time and Date (HR:MN DD-MMM-YYYY) [S]:
>tim
20:33:00 14-Nov-2021
>acs sy:/blks=512
>set /colog=on
>set /colog/nocoterm
>pip [syslog]*.*/pu:50
>upt
Up 0 days, 0 hours, 0 minutes and 5.80 seconds.
>@ <EOF>
>cd build
>@sysgen
>; This command file will build a system image file consisting of the kernel
>; and device drivers.
>;
>; After this step, privileged utilities should be rebuilt and the system
>; image configured with VMR to create memory partitions and to install the
>; minimum necessary tasks.
>;
>rem ...lbr
>ins $lbr/inc=35000
>* Do you want assembly listing? [Y/N D:F]:
>* Do you want build map listing? [Y/N D:T]:
>;
>; Compiling device drivers
>;
>set /dir=[drvsrc]
>mac @compile
>lbr drivers.lib=devdu/e+devtt/e+devnl/e+devco/e+pseudo/e
>pip [build]=drivers.lib/nv
>pip compile.cmd;*,*.obj;*,*.lib;*/de
>;
>; Compiling the kernel modules
>;
>set /dir=[syssrc]
>mac @compile
>lbr @combine
>pip compile.cmd;*,combine.cmd;*/de
>mac @compile
>pip [build]=kernel.lib/nv,startup.obj/nv,init.obj/nv,sysdat.obj/nv
>pip compile.cmd;*,*.obj;*,*.lib;*/de
>;
>; Building the system image
>;
>set /dir=[build]
>tkb @build
>;
>; Creating the system symbol definition file for privileged tasks
>;
>mac =sym2inc/i$
>tkb sym2inc=sym2inc,$fcslib/lb,$syslib/lb/task=...S2I/ext=2000
>pip *.obj;*,*.lib;*/de
>run sym2inc
>;
>; Done.
>;
>@ <EOF>
>dir

Directory DU4:[BUILD]
14-Nov-2021 20:38:26

SYSGEN   .CMD;1          2753    14-Nov-2021 15:43:15
SYM2INC  .MAC;1         10256    14-Nov-2021 13:57:29
SYSTEM   .DAT;1          3152    22-Apr-2020 21:07:00
SYSTEM   .INC;1          3889    14-Nov-2021 20:34:01
BUILD    .CMD;1           107    14-Nov-2021 20:33:54
SYSTEM   .SYM;1          2432 C  14-Nov-2021 20:33:58
SYM2INC  .TSK;1          4736 C  14-Nov-2021 20:34:00
SYSTEM   .MAP;1          6272 C  14-Nov-2021 20:33:57
SYSTEM   .SYS;1         63872 C  14-Nov-2021 20:33:57

Total of 97469 bytes in 9 files.

>
```

**Comment by vandys** [comment]
That's great!  I'll send you the vol180 changes soon, just want to make my initial submission as perfect as possible!

**Comment by vandys** [comment]
Ok, here's my proposed patch!
[import_dir_pat.txt](https://github.com/hperaza/RSX280/files/7534892/import_dir_pat.txt)

**Comment by hperaza** [comment]
Thanks! Applied.
